import Head from "next/head";
import { Container, Card, Row, Text } from "@nextui-org/react";
import { Header } from "@/components/Header";
import axios from "axios";
import fs from "fs/promises";
import Link from "next/link";
import Image from "next/image";

export default function Home({ latestComics }) {
  console.log(latestComics);
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <h2 className="text-3xl font-bold text-center">Latest Comics</h2>
          <section className="grid grid-cols-2 gap-2 max-w-md m-auto">
            {latestComics.map((comic) => {
              return (
                <Link href={`/comic/${comic.id}`} key={comic.id}>
                  <Image
                    width={500}
                    height={500}
                    src={comic.img}
                    alt={comic.alt}
                    objectFit="cover"
                  />
                </Link>
              );
            })}
          </section>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const files = await fs.readdir("./comics");
  const latestComicsFiles = files.slice(-8, files.length);

  const promisesReadFiles = latestComicsFiles.map(async (file) => {
    const content = await fs.readFile(`./comics/${file}`, "utf8");
    return JSON.parse(content);
  });
  const latestComics = await Promise.all(promisesReadFiles);
  console.log(latestComics);
  return {
    props: {
      latestComics,
    },
  };
}
